packages:
  - apps/*
  - packages/*
  - tooling/*
  - docs


catalog:
  "@tanstack/react-query": 5.59.15
  "@trpc/client": 11.0.0-rc.593
  "@trpc/react-query": 11.0.0-rc.593
  "@trpc/server": 11.0.0-rc.593
  tailwindcss: 3.4.14
  typescript: 5.6.3
  superjson: 2.2.1
  zod: 3.23.8
  "@mantine/hooks": 7.13.3
  "@auth/core": 0.37.2
  "@t3-oss/env-nextjs": 0.11.1
  "@types/node": 20.16.14
  "dotenv-cli": 7.4.2
  jiti: 2.3.3
  "@tabler/icons-react": 3.19.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": 18.3.11
    "@types/react-dom": 18.3.1
